### ISSUE TITLE
Meaningful example screenshot for CJK characters

### ISSUE THREAD

**Issue by jasonslyvia** [jonathanslenders/pyvim#14]
The screenshot in README for Chinese input displays weird Chinese characters, at least it's not Simplified Chinese nor Traditional Chinese. It might send a misleading signal to Chinese developers that pyvim display Chinese characters in gibberish.

I suggest using following text (Simplified Chinese) in the screenshot:

```
pyvim 是 Vi 的 Python 克隆版。目前本项目正处于开发阶段，但已基本可用。如果你有任何的疑惑或者发现了任何 bug，请通过 GitHub Issues 反馈。
```

Which means:

```
pyvim is a Vi clone in Python. It's under development but it's certainly usable. If you have any questions or find any bug, please feedback in GitHub Issues.
```

**Comment by coolwanglu** [comment]
I agree, yet I would recommend something interesting:
Chinese sample text, all character have the same syllable. [wiki](http://en.wikipedia.org/wiki/Lion-Eating_Poet_in_the_Stone_Den)
```
石室诗士施氏，嗜狮，誓食十狮。适施氏时时适市视狮。十时，适十狮适市。是时，适施氏适市。氏视是十狮，恃矢势，使是十狮逝世。氏拾是十狮尸，适石室。石室湿，氏使侍拭石室。石室拭，氏始试食是十狮尸。食时，始识是十狮尸，实十石狮尸。试释是事。
```

Japanese sample text, from a famous novel.[wiki](http://en.wikipedia.org/wiki/I_Am_a_Cat)
```
　吾輩わがはいは猫である。名前はまだ無い。
　どこで生れたかとんと見当けんとうがつかぬ。何でも薄暗いじめじめした所でニャーニャー泣いていた事だけは記憶している。吾輩はここで始めて人間というものを見た。しかもあとで聞くとそれは書生という人間中で一番獰悪どうあくな種族であったそうだ。この書生というのは時々我々を捕つかまえて煮にて食うという話である。しかしその当時は何という考もなかったから別段恐しいとも思わなかった。ただ彼の掌てのひらに載せられてスーと持ち上げられた時何だかフワフワした感じがあったばかりである。掌の上で少し落ちついて書生の顔を見たのがいわゆる人間というものの見始みはじめであろう。この時妙なものだと思った感じが今でも残っている。第一毛をもって装飾されべきはずの顔がつるつるしてまるで薬缶やかんだ。その後ご猫にもだいぶ逢あったがこんな片輪かたわには一度も出会でくわした事がない。のみならず顔の真中があまりに突起している。そうしてその穴の中から時々ぷうぷうと煙けむりを吹く。どうも咽むせぽくて実に弱った。これが人間の飲む煙草たばこというものである事はようやくこの頃知った。
```

**Comment by jasonslyvia** [comment]
That's a interesting idea!

**Comment by vczh** [comment]
Agree. Unmeaningful Chinese characters just make us feel like there is a encoding problem.

**Comment by jonathanslenders** [comment]
Thanks for the suggestion! I made a new screenshot with the text of @coolwanglu.
(The original was from a lorem ipsum generator.)
