### ISSUE TITLE
Ctrl-d causes delete instead of page-down

### ISSUE THREAD

**Issue by unanimousarc** [jonathanslenders/pyvim#18]
On Mac OS X using iTerm2

Ctrl-u causes half page-up as expected, whereas ctrl-d causes deletion of the character under the cursor instead of page-down as expected

**Comment by jonathanslenders** [comment]
Good catch! That's the default key binding of readline what you experience.
In a shell, ControlD will delete. I will create a new key binding for pyvim.
Thanks.

**Comment by SanketDG** [comment]
As much as I understand the code I think `Ctrl-F`is set to scroll half page down. But it actually should scroll full page down.

- `Ctrl-B` and `Ctrl-F` scroll by full page.
- `Ctrl-U` and `Ctrl-D` scroll half a page by default.
- `Ctrl-Y` and `Ctrl-E` scroll one line.

**Comment by jonathanslenders** [comment]
@SanketDG Thank you! That is a huge help. I couldn't figure out how much they should scroll. I will fix that.

**Comment by SanketDG** [comment]
Please take a look at #23

**Comment by lunemec** [comment]
Also pageup and pagedown buttons are not working - full screen scroll.

**Comment by jonathanslenders** [comment]
Normally, all of these should be working.
Control B/F/U/D/Y/E as well as PageUp and PageDown.

(That is the latest master commit. Not yet the Pypi version.)

**Comment by lunemec** [comment]
Oh, I have pypi version installed.

**Comment by SanketDG** [comment]
Well you can clone this and then run `python setup.py install` from the pyvim folder. That should get you the latest master branch.

**Comment by lunemec** [comment]
I know :) doing it right now ;)

**Comment by lunemec** [comment]
Yes, these seem to work in master. ctrl-d works too.. you can close this issue :)
