### ISSUE TITLE
:o :open not working

### ISSUE THREAD

**Issue by lunemec** [jonathanslenders/pyvim#27]
in pyvim there is :e and :edit, but vim uses :o and :open for these as well.

**Comment by jonathanslenders** [comment]
Are these just aliases, or do they have a different meaning?

**Comment by lunemec** [comment]
From my tests and what I could find online they seem to be aliases. Also when you press :e or :o again, it re-reads the file currently being edited from disk for changes from other programs (git or other editor) or tells you you have unsaved changes and the file has been changed on disk.

**Comment by lunemec** [comment]
from vim's :help open

*:o* *:op* *:open*
:[range]o[pen]			Works like |:visual|: end Ex mode.
				{Vi: start editing in open mode}

:[range]o[pen] /pattern/	As above, additionally move the cursor to the
				column where "pattern" matches in the cursor
				line.

Vim does not support open mode, since it's not really useful.  For those
situations where ":open" would start open mode Vim will leave Ex mode, which
allows executing the same commands, but updates the whole screen instead of
only one line.

**Comment by jonathanslenders** [comment]
Thank you. I didn't know about the re-read part. That is interesting.

**Comment by jonathanslenders** [comment]
This has been implemented: https://github.com/jonathanslenders/pyvim/commit/40cfe6691aef91262eb30ca8d415c437331ba104
