### ISSUE TITLE
Visual inside word and () not working

### ISSUE THREAD

**Issue by lunemec** [jonathanslenders/pyvim#37]
In vim, when you press viw it select visual inside word and selects entire word. Now in pyvim it only selects from current cursor position.

Also vi) or vi( visual inside () is not working.

Visual around also is not working. va( va) vaw ... visual around () or visual around word.

**Comment by jonathanslenders** [comment]
Thanks a lot for reporting this!
I didn't know about it, but it definitely makes sense. It's actually an enhancement that goes to prompt-toolkit.  Having this also means that when I implement "ap" (Auto-paragraph), we will automatically have "vap" as well.

**Comment by jonathanslenders** [comment]
Fixed in https://github.com/jonathanslenders/python-prompt-toolkit/commit/3675addf7e3f65f63ab833cfcb5cf3205e54fac2

This should handle:  viw, vaw, vi(, vi{ va( va{, etc...
