### ISSUE TITLE
Named yank buffers not working

### ISSUE THREAD

**Issue by lunemec** [jonathanslenders/pyvim#38]
Named buffers are not working: shortcuts "3y  - yank selected into buffer number 3 .. instead of numbers it can contain also letters "ay (yank buffer a). You paste this with "3p or "ap.
```
							*v_y*
{Visual}["x]y		Yank the highlighted text [into register x] (for
			{Visual} see |Visual-mode|).  {not in Vi}

							*v_Y*
{Visual}["x]Y		Yank the highlighted lines [into register x] (for
			{Visual} see |Visual-mode|).  {not in Vi}
```

**Comment by jonathanslenders** [comment]
This has to be implemented in prompt-toolkit itself:
https://github.com/jonathanslenders/python-prompt-toolkit/issues/207

I'm closing this issue in favor of that one.
