### ISSUE TITLE
Function names in pyvim/commands/commands.py

### ISSUE THREAD

**Issue by lunemec** [jonathanslenders/pyvim#48]
Aside from pep8 screaming of redefining of the same function name all the time, wouldn't there be upside to naming those functions for debugging purposes? Now when you'd print COMMANDS_TO_HANDLERS dict, you'd only get {'shortcut': <function _ 0x...>} and there is no telling them apart. While now this is OK, you can find the function by the @cmd decorator, when there is a ton of shortcuts, it'd be much better to have those functions with name.

If you agree, I'll send pull request with renaming.

**Comment by jonathanslenders** [comment]
I agree. Feel free to create a pull request.

**Comment by lunemec** [comment]
https://github.com/jonathanslenders/pyvim/pull/57
