### ISSUE TITLE
Visual selected block + d not working, works with + dd

### ISSUE THREAD

**Issue by lunemec** [jonathanslenders/pyvim#52]
When you have selected block visually, you can just press (c,d, ...) and the action should work. This works for visual select + c (as in change) but for deleting, you need to press *d* twice. This is incorrect.

**Comment by jonathanslenders** [comment]
That's a bug. Thanks! Will be fixed.

**Comment by jonathanslenders** [comment]
Fixed in: https://github.com/jonathanslenders/python-prompt-toolkit/commit/3228e1c4c3373a167d4685288e29f316ab6bd8e2
