### ISSUE TITLE
Ctrl+t does strange things

### ISSUE THREAD

**Issue by lunemec** [jonathanslenders/pyvim#56]
I'm not sure what <C-t> is supposed to do, but when you apply it on line that has correct indent:
```
def _(attr):
```
it creates:
```
de f_(attr):
```
I'm not sure if this is desired behavior.

**Comment by jonathanslenders** [comment]
I think in insert mode, in indents, while in navigation mode it still replaces the last two characters before the cursor. That's what GNU readline does, but we shouldn't do that.

**Comment by jonathanslenders** [comment]
Fixed: https://github.com/jonathanslenders/pyvim/commit/1fdd937b4cb1592703b66c59247358c2473f4104
