### ISSUE TITLE
please also make pyvim as python executable module, which can be started as: "python -m pyvim"

### ISSUE THREAD

**Issue by zaxebo1** [jonathanslenders/pyvim#63]
after installation we need to type pyvim to run it, which is fine.

 **please pyvim be also made a executable module** , such that we can run it using

```
    python -m pyvim
````

****

It will be useful when there are multiple installation of python on the system - such as python3.3 ,python3.4 ,python 3.5 , and i want to install it in particular python and launch it from there as:

````
    mypip3.4 install pyvim     #this is already do-able,obviously
    mypython3.4 -m pyvim    #this needs t be supported
````

**Comment by jonathanslenders** [comment]
Hi @zaxebo1,

Thanks for the recommendation! It should now work: https://github.com/jonathanslenders/pyvim/commit/ce65f7a98d72f156cb768ffdf91859cf0e5c54b3

Cheers,
Jonathan

**Comment by zaxebo1** [comment]
@jonathanslenders 
awesome. Thanks for solving this request
and thanks a ton for writing this software

**Comment by jonathanslenders** [comment]
You're welcome!

**Comment by zaxebo1** [comment]
has it be released over pip? 

**as you have suggested at  https://github.com/jonathanslenders/pyvim i installed it following steps**
that to install pyvim , i did:
   pip3 uninstall pyvim
   pip3 install pyvim

but, when i launch it with python3 -m pyvim
**then it did not worked**
