### ISSUE TITLE
zt and zb not working

### ISSUE THREAD

**Issue by rgkirch** [jonathanslenders/pyvim#65]
I don't know if these controls are not supposed to work but as 'zz' works it seems incomplete to leave out 'zt' and 'zb'. Does this work for you? Is it actually a bug?

**Comment by amjith** [comment]
Looks like `zt` is the same as `z<cr>` and `zb` is the same as `z-` which is already implemented. So it should be easy to add them.

**Comment by rgkirch** [comment]
Aha, I didn't know about those until now. Then `zt` should be mapped to what `z<cr>` does but `z<cr>` needs to be modified a little so that the cursor resets to the first column after scrolling. Similarly `zb` should be mapped to what `z-` does and `z-` should be modified.
Thanks for teaching me more short-cuts.

**Comment by jonathanslenders** [comment]
That pull request of @amjith has been merged, so the next pyvim release will include it. Thanks everyone!
