### ISSUE TITLE
Undoing rectangular copy/paste doesn't work

### ISSUE THREAD

**Issue by davidbrochart** [jonathanslenders/pyvim#76]
Ctrl-v and select a rectangle, y to yank, p to paste.
Then u to undo: it is actually undone but the screen is not refreshed.

**Comment by jonathanslenders** [comment]
Thanks a lot for reporting this! I appreciate it.
The solution was actually easy: https://github.com/jonathanslenders/python-prompt-toolkit/commit/6d14961008cc00dba8ffb5b1d72753134baf9084
This is a serious bug, so it means that I will push a new release asap.
